showNewVersionIcon: true
theme: 1
hideAfterStartup: true
randomControllerPort: true
connProxy: 1
connProfile: false
showProxyFilter: true
mixinText: >-
  mixin: # object
    dns:
      enable: true
      enhanced-mode: fake-ip #redir-host
      nameserver:
        - 8.8.8.8 # 真实请求DNS，可多设置几个
        - 114.114.114.114
        - https://dns.rubyfish.cn/dns-query
        - https://223.5.5.5/dns-query
        - https://dns.pub/dns-query
      fake-ip-filter:                # fake ip white domain list, aka Always Real IP
      - "dns.msftncsi.com"
      - "www.msftncsi.com"
      - "www.msftconnecttest.com"
    # interface-name: WLAN # 出口网卡名称，或者使用下方的自动检测
    tun:
      enable: true
      stack: gvisor
      dns-hijack:
        - 198.18.0.2:53
      macOS-auto-route: true
      macOS-auto-detect-interface: true # 自动检测出口网卡
bypassText: |
  bypass:
    - "*msftconnecttest.com"
    - "*c-msedge.net"
    - "edge.microsoft.com"
    - localhost
    - 127.*
    - 10.*
    - 172.16.*
    - 172.17.*
    - 172.18.*
    - 172.19.*
    - 172.20.*
    - 172.21.*
    - 172.22.*
    - 172.23.*
    - 172.24.*
    - 172.25.*
    - 172.26.*
    - 172.27.*
    - 172.28.*
    - 172.29.*
    - 172.30.*
    - 172.31.*
    - 192.168.*
    - <local>
systemProxyTypeIndex: 0
showNotifications: false
connShowType: 0
connKeepOld: false
pacContentText: >-
  function FindProxyForURL(url, host) {
    if (isPlainHostName(host) || dnsDomainIs(host, ".msftconnecttest.com")) {
      return "DIRECT";
    } else {
    return "PROXY 127.0.0.1:%mixed-port%; SOCKS5 127.0.0.1:%mixed-port%; DIRECT;"
    }
  }
lightweightMode: false
iconSpeed: false
systemTheme: true
trayText: ""
trayColorTransparent: false
editor: 0
specifyHttpProxyProtocol: true
